# Generated by Django 4.2.3 on 2023-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
